In [2]:
# Importing necessary libraries
import pandas as pd
import numpy as np

In [3]:
np.arange(20).reshape(5,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
df = pd.DataFrame(np.arange(20).reshape(5,4), columns=['column1', 'column2', 'column3', 'column4'])
df

column1  column2  column3  column4
0        0        1        2        3
1        4        5        6        7
2        8        9       10       11
3       12       13       14       15
4       16       17       18       19

In [5]:
np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
pd.DataFrame(data= np.arange(20).reshape(5,4),index= ['row0', 'row1', 'row2', 'row3', 'row4'], columns=['column0', 'column1', 'column2', 'column3'])


column0  column1  column2  column3
row0        0        1        2        3
row1        4        5        6        7
row2        8        9       10       11
row3       12       13       14       15
row4       16       17       18       19

In [7]:
# We have to give 5 row names and 4 column names as we have 5 rows and 4 columns
df = pd.DataFrame(data= np.arange(20).reshape(5,4),index= ['row0', 'row1', 'row2', 'row3', 'row4'], columns=['column0', 'column1', 'column2', 'column3'])
print(df)

      column0  column1  column2  column3
row0        0        1        2        3
row1        4        5        6        7
row2        8        9       10       11
row3       12       13       14       15
row4       16       17       18       19


In [8]:
df.head()

column0  column1  column2  column3
row0        0        1        2        3
row1        4        5        6        7
row2        8        9       10       11
row3       12       13       14       15
row4       16       17       18       19

In [9]:
# DataFrame is type of data structure in pandas
type(df)

pandas.core.frame.DataFrame

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row0 to row4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column0  5 non-null      int64
 1   column1  5 non-null      int64
 2   column2  5 non-null      int64
 3   column3  5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes


In [11]:
df.describe()

column0    column1    column2    column3
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [12]:
## Indexing and Selection in DataFrame
## column name , rowindex[loc],row index column index[iloc],index number[.iloc]
df.head()

column0  column1  column2  column3
row0        0        1        2        3
row1        4        5        6        7
row2        8        9       10       11
row3       12       13       14       15
row4       16       17       18       19

In [13]:
# Retrieving a single column
df['column1']


row0     1
row1     5
row2     9
row3    13
row4    17
Name: column1, dtype: int64

In [14]:
# Retrieving a single column
df.column1

row0     1
row1     5
row2     9
row3    13
row4    17
Name: column1, dtype: int64

In [15]:
type(df['column1'])

pandas.core.series.Series

In [16]:
# Retrieving multiple columns
df[['column1', 'column2']]

column1  column2
row0        1        2
row1        5        6
row2        9       10
row3       13       14
row4       17       18

In [17]:
# Type of Series
type(df["column1"])

pandas.core.series.Series

In [18]:
# Type of DataFrame
type(df[['column1', 'column2']])

pandas.core.frame.DataFrame

In [19]:
# This will give error as row1 is not a column name
# type(df["row1"])  

In [20]:
df.head()

column0  column1  column2  column3
row0        0        1        2        3
row1        4        5        6        7
row2        8        9       10       11
row3       12       13       14       15
row4       16       17       18       19

In [21]:
# 
df.loc['row1']  # This will give row1 data as row1 is an index name

column0    4
column1    5
column2    6
column3    7
Name: row1, dtype: int64

In [22]:
df.loc['row2'] 

column0     8
column1     9
column2    10
column3    11
Name: row2, dtype: int64

In [23]:
# Type of Series
type(df.loc['row1'])  # This will give series as output , series is 1D array , it is simply a row

pandas.core.series.Series

In [24]:
# This will give error as column1 is not an index name
# df.loc["column1"]  

In [25]:
# Retrieving multiple  using row index names loc
df.loc[['row1', 'row2']] # This will give multiple rows as output

column0  column1  column2  column3
row1        4        5        6        7
row2        8        9       10       11

In [26]:
df.head()  # First 5 rows

column0  column1  column2  column3
row0        0        1        2        3
row1        4        5        6        7
row2        8        9       10       11
row3       12       13       14       15
row4       16       17       18       19

In [27]:
# Using row index loc and index number
df.iloc[2:4,0:2] # [row start:row stop, column start:column stop]  # This will give rows from index 2 to 3 , 4 is excluded

column0  column1
row2        8        9
row3       12       13

In [28]:
#
df.iloc[2:5,2:4]

column2  column3
row2       10       11
row3       14       15
row4       18       19

In [29]:
df.head()

column0  column1  column2  column3
row0        0        1        2        3
row1        4        5        6        7
row2        8        9       10       11
row3       12       13       14       15
row4       16       17       18       19

In [30]:
# Selecting specific columns using index number
df.iloc[:,[0,3]]  # This will give all rows and column0 and column3

column0  column3
row0        0        3
row1        4        7
row2        8       11
row3       12       15
row4       16       19

In [31]:
df.head()

column0  column1  column2  column3
row0        0        1        2        3
row1        4        5        6        7
row2        8        9       10       11
row3       12       13       14       15
row4       16       17       18       19

In [32]:
# convert dataframe to numpy array
df.iloc[:,1:].values # This will give all rows and column1 to last column

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [33]:
#checking null values
df.isnull().sum()

column0    0
column1    0
column2    0
column3    0
dtype: int64

In [34]:

df = pd.DataFrame(data= [[1,np.nan,2],[1,3,4]],index= ['row0', 'row1'], columns=['column0', 'column1', 'column2'])
df

column0  column1  column2
row0        1      NaN        2
row1        1      3.0        4

In [35]:
df.isnull().sum()

column0    0
column1    1
column2    0
dtype: int64

In [36]:
df.isnull()

column0  column1  column2
row0    False     True    False
row1    False    False    False

In [37]:
df.isnull().sum()==0 # This will give True if there is no null value in that column else False

column0     True
column1    False
column2     True
dtype: bool

In [38]:
df.isnull().sum()==1 # 

column0    False
column1     True
column2    False
dtype: bool

In [39]:
df["column2"].value_counts() # This will give count of unique values in that column

column2
2    1
4    1
Name: count, dtype: int64

In [40]:
df['column2'].unique() # This will give unique values in that column

array([2, 4])

In [41]:
# We have to give 5 row names and 4 column names as we have 5 rows and 4 columns
df = pd.DataFrame(data= np.arange(20).reshape(5,4),index= ['row0', 'row1', 'row2', 'row3', 'row4'], columns=['column0', 'column1', 'column2', 'column3'])
print(df) # This will give the dataframe with 5 rows and 4 columns

      column0  column1  column2  column3
row0        0        1        2        3
row1        4        5        6        7
row2        8        9       10       11
row3       12       13       14       15
row4       16       17       18       19


In [42]:
df>2 # This will give boolean values True and False , which is greater than 2 will be True else False

column0  column1  column2  column3
row0    False    False    False     True
row1     True     True     True     True
row2     True     True     True     True
row3     True     True     True     True
row4     True     True     True     True

In [43]:
df.head()

column0  column1  column2  column3
row0        0        1        2        3
row1        4        5        6        7
row2        8        9       10       11
row3       12       13       14       15
row4       16       17       18       19

In [44]:
# conditional indexing
df[df["column3"]>10] # This will give all rows where column3 value is greater than 10

column0  column1  column2  column3
row2        8        9       10       11
row3       12       13       14       15
row4       16       17       18       19